[package]
name = "arythmitical/typedenum"
description = "Construct custom enums at runtime, with proper autocompletion and typechecking."
version = "1.0.4"
license = "MIT"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
homepage = "https://arythmitical.github.io/TypedEnum"
repository = "https://github.com/arythmitical/TypedEnum"
exclude = ["**"]
include = [
	"src",
	"src/**",
	"example",
	"example/**",
	"docs",
	"docs/**",
	"README.md",
	"LICENSE.txt",
	"default.project.json",
	"wally.toml",
]
