name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Lune
        run: |
          cd ${{ github.workspace }}
          mkdir build
          cd build
          curl -L "https://github.com/lune-org/lune/releases/download/v0.10.1/lune-0.10.1-linux-x86_64.zip" -o lune-binary.zip
          unzip lune-binary.zip
          chmod +x lune
          cd ..

      - name: Run build.luau
        run: |
          build/lune run lune/build.luau

      - name: Upload .rbxm file
        uses: actions/upload-artifact@v4
        with:
          name: TypedEnum.rbxm
          path: build/TypedEnum.rbxm
          if-no-files-found: error

      - name: Upload .luau file
        uses: actions/upload-artifact@v4
        with:
          name: TypedEnum.luau
          path: build/TypedEnum.luau
          if-no-files-found: error
